
#Name of the project
PROJECT: TRIAL2

#Name of the analysis run
RUN: ARMS_4_SAMPLES

#Metadata for the sequencing run:
#Here values can be added that are shared across all samples (can also be added to the sample data csv file if wanted).
#Values that differ between samples should be added to the sample_data_template.csv file!
meta:
  sampling:
    sample_data_file: config/sample_data_template_4samples.csv
  sequencing:
    target_gene: COI
    subfragment: 5P
    pcr_primer_forward: GGWACWGGWTGAACWGTWTAYCCYCC
    pcr_primer_reverse: TANACYTCNGGRTGNCCRAARAAYCA
    pcr_primer_name_forw: mlCOIintF
    pcr_primer_name_reverse: jgHCO2198
    pcr_primer_reference:  doi:10.1186/1742-9994-10-34
    lib_layout: Paired
    seq_meth: IlluminaMiseq
    sop: http://www.assembleplus.eu/sites/assembleplus.eu/files/public/ARMS/ARMS_MSOPs.pdf
    extra_fields: My_name:Saara,The_Project:PacMAN

#Csv file of the samples that should be analysed.
#This needs to have three columns: sample-id,absolute-filepath,direction
#Where absolute filepath points to each samples forward and reverse files separately
#direction is either 'forward' or 'reverse'
SAMPLE_SET: config/manifest_pe_4samples.csv

#TRIMMOMATIC
trimmomatic:
  ILLUMINACLIP: resources/adapters/NexteraPE-PE.fa:2:30:15
  LEADING: 10
  TRAILING: 15
  MAXINFO: 200\:0.3
  extra_params: ""

#CutAdapt
cutadapt:
  forward_primer: GGWACWGGWTGAACWGTWTAYCCYCC
  reverse_primer: TANACYTCNGGRTGNCCRAARAAYCA
  rc_forward_primer: GGRGGRTAWACWGTTCAWCCWGTWCC
  rc_reverse_primer: TGRTTYTTYGGNCAYCCNGARGTNTA
  extra_params: ""
  se_extra_params: ""

#dada2
#We include here all available parameters, so that the user has full control
#over the dada2 calculation. Most of these are populated by default values
#Those that are most often changed are: Trunc_len, TruncQ, minLen, and maxEE
DADA2:

  filterAndTrim:
    Trunc_len_f: 200
    Trunc_len_r: 150
    TruncQ: 2
    Trim_right: 0
    Trim_left: 0
    maxLen: Inf
    minLen: 20
    maxN: 0
    minQ: 0
    MaxEE: Inf
    Rm.phix: TRUE
    orient.fwd: NULL
    matchIDs: FALSE
    id.sep: \\s
    id.field: NULL
    compress: TRUE
    multithread: TRUE
    n: 100000
    OMP: TRUE
    verbose: FALSE

#DADA2 anaylysis part2 ######################

  learnERRORS:
    multithread: TRUE
    nbases: 1e8
    #errorEstimationFunction: see dada
    randomize: FALSE
    MAX_CONSIST: 10
    OMEGA_C: 0
    verbose: FALSE

  plotERRORS:
    #nti/ntj depict the nucleotides that
    nti: ACTG
    ntj: ACTG
    obs: TRUE
    err_out: TRUE
    err_in: FALSE
    nominalQ: TRUE

  derepFastq:
    n: 1e6

  dada:
    errorEstimationFunction: loessErrfun
    selfConsist: FALSE
    pool: FALSE
    priors: NULL

  mergePairs:
    include: TRUE
    minOverlap: 12
    maxMismatch: 0
    returnRejects: FALSE
    propagateCol: NULL
    justConcatenate: FALSE
    trimOverhang: FALSE

  removeBimeraDenovo:
    method: consensus

#DATABASE
DATABASE:
  #The location of the bowtie2 database must be with the basename of the index FILES
  location_bowtie2: data/bowtie2_dbs/MIDORI_UNIQ_GB241_CO1/MIDORI_UNIQ_GB241_CO1
  name: MIDORI_UNIQ_GB241_CO1
  taxa: data/CO1_fasta_and_taxonomy/CO1_taxonomy.txt
  fasta: data/CO1_fasta_and_taxonomy/CO1_.fasta

#Taxonomy
TAXONOMY:
  threads: 3
  distinct_alignments: 100
  min_identity: 0.8
  min_length: 0.8
  #muscle: /Users/saara/Documents/OBIS_work/github/bioinformatics/PacMAN-pipeline/scripts/muscle
  bootstrap_no: 100
  match_score: 1
  mismatch_penalty: -2.5
  gap_penalty: -2
  blca_identity_cutoff: 100

#Darwin_core Formatting
